# Middleware configuration for Traefik
http:
  middlewares:
    # Redirect HTTP to HTTPS
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
    
    # Add security headers
    security-headers:
      headers:
        # Force HTTPS for one year including subdomains
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        
        # Prevent MIME type sniffing
        customRequestHeaders:
          X-Content-Type-Options: nosniff
        
        # Enable XSS protection
        customResponseHeaders:
          X-XSS-Protection: "1; mode=block"
        
        # Prevent clickjacking
        customFrameOptionsValue: "SAMEORIGIN"
        
        # Set content security policy
        customRequestHeaders:
          Content-Security-Policy: |
            default-src 'self';
            script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net;
            style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net;
            img-src 'self' data: https:;
            font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net;
            connect-src 'self' https://api.sentiment.yourdomain.com;
            frame-ancestors 'self';
            form-action 'self';
            base-uri 'self';
            object-src 'none';
    
    # Rate limiting
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        
    # Basic authentication (optional, for specific routes)
    basic-auth:
      basicAuth:
        users:
          - "$2y$05$92sR5ePxqXo4Xr5ZR8X5.evUjLqQJYv5X8wXzZvJ6qXK3yV1XJ6qO"  # admin:admin (change in production)
    
    # IP Whitelist (example)
    ip-whitelist:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.1.0/24"
    
    # CORS configuration
    cors-headers:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowOriginList:
          - "https://sentiment.yourdomain.com"
          - "https://api.sentiment.yourdomain.com"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true
        
    # Compress responses
    compress:
      compress: {}
    
    # Remove specific headers
    strip-prefix:
      stripPrefix:
        prefixes:
          - "/api"
